services:
  - type: web
    name: bookbuddy-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://bookbuddy-backend-i99j.onrender.com/api
      - key: NODE_ENV
        value: production